---
services:
  - name: system-healthcheck.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/system-healthcheck.service 
  - name: system-healthcheck-sidekick.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/system-healthcheck-sidekick.service
  - name: fleet-unit-healthcheck.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/fleet-unit-healthcheck.service
  - name: fleet-unit-healthcheck-sidekick.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/fleet-unit-healthcheck-sidekick.service
  - name: vulcan.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/vulcan.service
  - name: diamond.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/diamond.service
  - name: elb-presence.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/elb-presence.service
  - name: image-cleaner.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/image-cleaner.service
  - name: image-cleaner.timer
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/image-cleaner.timer
  - name: elasticsearch@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/elasticsearch@.service
    count: 1
  - name: elasticsearch-sidekick@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/elasticsearch-sidekick@.service
    count: 1
  - name: restorage-es@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/restorage-es@.service
    count: 1
  - name: restorage-es-sidekick@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/restorage-es-sidekick@.service
    count: 1
  - name: kibana@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/kibana@.service
    count: 1
  - name: kibana-sidekick@.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/kibana-sidekick@.service
    count: 1
  - name: vulcan-config-builder.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/elasticSearch/vulcan-config-builder.service    
  - name: tunnel-registrator.service
    uri: https://raw.githubusercontent.com/Financial-Times/fleet/master/tunnel-registrator.service
